# THE VESSEL CODE — Paste keys when prompted; rest is automatic (TVC No1 pilot).
# Run from repo root:  .\deploy\QUICK-PASTE-SETUP.ps1

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
$EnvFile = Join-Path $Root 'deploy\.env.deploy.local'
$PilotVessel = 'TVC No1'

Write-Host ''
Write-Host 'TVC-PMS Online Sync — Quick Paste Setup' -ForegroundColor Cyan
Write-Host "Pilot vessel: $PilotVessel (one Supabase project for all vessels later)" -ForegroundColor Yellow
Write-Host '================================================================' -ForegroundColor Cyan
Write-Host ''

$supabaseUrl = Read-Host 'Paste SUPABASE_URL'
$serviceKey = Read-Host 'Paste SUPABASE_SERVICE_ROLE_KEY'
$dbUrl = Read-Host 'Paste DATABASE_URL'
$vercelToken = Read-Host 'Paste VERCEL_TOKEN'

Write-Host ''
Write-Host 'Looking up Vercel project ID...' -ForegroundColor Cyan
$env:VERCEL_TOKEN = $vercelToken
$listOut = node (Join-Path $Root 'scripts\list-vercel-projects.mjs') 2>&1
Write-Host $listOut
$projectId = Read-Host 'Paste VERCEL_PROJECT_ID for thevesselcode-pms (prj_...)'

$content = @"
# Auto-generated by QUICK-PASTE-SETUP.ps1 — do not commit
SUPABASE_URL=$supabaseUrl
SUPABASE_SERVICE_ROLE_KEY=$serviceKey
DATABASE_URL=$dbUrl
VERCEL_TOKEN=$vercelToken
VERCEL_PROJECT_ID=$projectId
SYNC_PILOT_VESSEL_ID=$PilotVessel
VERCEL_GIT_REPO=kckimmarine/thevesselcode-pms
VERCEL_GIT_REF=master
"@

Set-Content -Path $EnvFile -Value $content -Encoding UTF8
Write-Host ''
Write-Host "Saved $EnvFile" -ForegroundColor Green
Write-Host 'Running npm run setup-online-sync ...' -ForegroundColor Cyan
Write-Host ''

Push-Location $Root
try {
    npm run setup-online-sync
} finally {
    Pop-Location
}

Write-Host ''
Write-Host 'If verify shows 404 for TVC No1, setup succeeded (no package uploaded yet).' -ForegroundColor Yellow
Write-Host 'Test: Master Push to HQ -> HQ Pull from vessel.' -ForegroundColor Yellow
