/** IMPA STORE seed — generated by scripts/build-impa-catalog.mjs */
export type ImpaSeedItem = {
  impa_code: string;
  code: string;
  name: string;
  unit: string;
  category: string;
  rob: number;
  catalog_page: string;
  specs: Record<string, string>;
};

export const IMPA_SEED: ImpaSeedItem[] = [
  {
    "impa_code": "330101",
    "code": "330101",
    "name": "Rope Manila 32mm",
    "unit": "COIL",
    "category": "Rigging",
    "rob": 4,
    "catalog_page": "/data/impa-catalog-pages/rigging.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Rigging",
      "Material": "Manila hemp",
      "Standard": "ISO 1140 / ISO 2408"
    }
  },
  {
    "impa_code": "330102",
    "code": "330102",
    "name": "Wire Rope 12mm Galvanized",
    "unit": "MTR",
    "category": "Rigging",
    "rob": 120,
    "catalog_page": "/data/impa-catalog-pages/rigging.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Rigging",
      "Material": "Galvanized steel",
      "Standard": "ISO 1140 / ISO 2408"
    }
  },
  {
    "impa_code": "330201",
    "code": "330201",
    "name": "Shackle Bow Type 25T",
    "unit": "PCS",
    "category": "Rigging",
    "rob": 12,
    "catalog_page": "/data/impa-catalog-pages/rigging.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Rigging",
      "Material": "Manila hemp",
      "Standard": "ISO 1140 / ISO 2408"
    }
  },
  {
    "impa_code": "330301",
    "code": "330301",
    "name": "Paint Antifouling Red",
    "unit": "LTR",
    "category": "Paint",
    "rob": 80,
    "catalog_page": "/data/impa-catalog-pages/paint.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Paint",
      "Finish": "Matte antifouling",
      "Coverage": "8–10 m²/L",
      "VOC": "< 400 g/L"
    }
  },
  {
    "impa_code": "330302",
    "code": "330302",
    "name": "Paint Primer Epoxy Grey",
    "unit": "LTR",
    "category": "Paint",
    "rob": 45,
    "catalog_page": "/data/impa-catalog-pages/paint.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Paint",
      "Finish": "Epoxy primer",
      "Coverage": "8–10 m²/L",
      "VOC": "< 400 g/L"
    }
  },
  {
    "impa_code": "330401",
    "code": "330401",
    "name": "Brush Paint 100mm",
    "unit": "PCS",
    "category": "Paint",
    "rob": 24,
    "catalog_page": "/data/impa-catalog-pages/paint.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Paint",
      "Finish": "Epoxy primer",
      "Coverage": "8–10 m²/L",
      "VOC": "< 400 g/L"
    }
  },
  {
    "impa_code": "330501",
    "code": "330501",
    "name": "Grease Multi-Purpose NLGI 2",
    "unit": "KG",
    "category": "Lubricants",
    "rob": 36,
    "catalog_page": "/data/impa-catalog-pages/lubricants.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Lubricants",
      "Grade": "NLGI 2",
      "Operating Temp": "-20°C to +120°C"
    }
  },
  {
    "impa_code": "330502",
    "code": "330502",
    "name": "Hydraulic Oil ISO 46",
    "unit": "LTR",
    "category": "Lubricants",
    "rob": 200,
    "catalog_page": "/data/impa-catalog-pages/lubricants.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Lubricants",
      "Grade": "ISO VG 46",
      "Operating Temp": "-20°C to +120°C"
    }
  },
  {
    "impa_code": "330601",
    "code": "330601",
    "name": "Filter Oil Engine",
    "unit": "PCS",
    "category": "Engine",
    "rob": 6,
    "catalog_page": "/data/impa-catalog-pages/engine.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Engine",
      "Application": "Primary filtration",
      "Service Interval": "Per PMS"
    }
  },
  {
    "impa_code": "330602",
    "code": "330602",
    "name": "Filter Fuel Primary",
    "unit": "PCS",
    "category": "Engine",
    "rob": 4,
    "catalog_page": "/data/impa-catalog-pages/engine.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Engine",
      "Application": "Primary filtration",
      "Service Interval": "Per PMS"
    }
  },
  {
    "impa_code": "330701",
    "code": "330701",
    "name": "Gasket Set Cylinder Head",
    "unit": "SET",
    "category": "Engine",
    "rob": 1,
    "catalog_page": "/data/impa-catalog-pages/engine.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Engine",
      "Application": "OEM replacement",
      "Service Interval": "Per PMS"
    }
  },
  {
    "impa_code": "330801",
    "code": "330801",
    "name": "Belt V-Type A-65",
    "unit": "PCS",
    "category": "Engine",
    "rob": 3,
    "catalog_page": "/data/impa-catalog-pages/engine.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Engine",
      "Application": "OEM replacement",
      "Service Interval": "Per PMS"
    }
  },
  {
    "impa_code": "330901",
    "code": "330901",
    "name": "Safety Helmet White",
    "unit": "PCS",
    "category": "Safety",
    "rob": 18,
    "catalog_page": "/data/impa-catalog-pages/safety.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Safety",
      "Certification": "ISO 12402",
      "Colour": "White"
    }
  },
  {
    "impa_code": "330902",
    "code": "330902",
    "name": "Safety Gloves Leather",
    "unit": "PR",
    "category": "Safety",
    "rob": 30,
    "catalog_page": "/data/impa-catalog-pages/safety.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Safety",
      "Certification": "ISO 12402",
      "Colour": "Standard"
    }
  },
  {
    "impa_code": "331001",
    "code": "331001",
    "name": "Life Jacket SOLAS",
    "unit": "PCS",
    "category": "Safety",
    "rob": 28,
    "catalog_page": "/data/impa-catalog-pages/safety.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Safety",
      "Certification": "SOLAS / MED",
      "Colour": "Standard"
    }
  },
  {
    "impa_code": "331101",
    "code": "331101",
    "name": "Fire Extinguisher CO2 5kg",
    "unit": "PCS",
    "category": "Safety",
    "rob": 8,
    "catalog_page": "/data/impa-catalog-pages/safety.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Safety",
      "Certification": "ISO 12402",
      "Colour": "Standard"
    }
  },
  {
    "impa_code": "331201",
    "code": "331201",
    "name": "Valve Gate Bronze 50mm",
    "unit": "PCS",
    "category": "Piping",
    "rob": 5,
    "catalog_page": "/data/impa-catalog-pages/piping.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Piping",
      "Nominal Size": "DN50 (2\")",
      "Pressure Class": "PN16",
      "Body Material": "Bronze / Steel"
    }
  },
  {
    "impa_code": "331202",
    "code": "331202",
    "name": "Flange Blind 50mm",
    "unit": "PCS",
    "category": "Piping",
    "rob": 4,
    "catalog_page": "/data/impa-catalog-pages/piping.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Piping",
      "Nominal Size": "DN50 (2\")",
      "Pressure Class": "PN16",
      "Body Material": "Bronze / Steel"
    }
  },
  {
    "impa_code": "331301",
    "code": "331301",
    "name": "Bolt Hex M16 x 60",
    "unit": "PCS",
    "category": "Fasteners",
    "rob": 150,
    "catalog_page": "/data/impa-catalog-pages/fasteners.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Fasteners",
      "Thread": "M16 × 2.0",
      "Length": "60 mm",
      "Grade": "8.8 / A4-80"
    }
  },
  {
    "impa_code": "331302",
    "code": "331302",
    "name": "Nut Hex M16",
    "unit": "PCS",
    "category": "Fasteners",
    "rob": 160,
    "catalog_page": "/data/impa-catalog-pages/fasteners.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Fasteners",
      "Thread": "M16 × 2.0",
      "Length": "—",
      "Grade": "8.8 / A4-80"
    }
  },
  {
    "impa_code": "331401",
    "code": "331401",
    "name": "Electrical Cable 3C 2.5mm²",
    "unit": "MTR",
    "category": "Electrical",
    "rob": 250,
    "catalog_page": "/data/impa-catalog-pages/electrical.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Electrical",
      "Voltage": "220 V AC",
      "Insulation": "PVC 3C",
      "Rating": "2.5 mm²"
    }
  },
  {
    "impa_code": "331402",
    "code": "331402",
    "name": "Lamp Fluorescent 20W",
    "unit": "PCS",
    "category": "Electrical",
    "rob": 20,
    "catalog_page": "/data/impa-catalog-pages/electrical.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Electrical",
      "Voltage": "220 V AC",
      "Insulation": "—",
      "Rating": "20 W"
    }
  },
  {
    "impa_code": "331501",
    "code": "331501",
    "name": "Cleaning Compound Degreaser",
    "unit": "LTR",
    "category": "Cleaning",
    "rob": 60,
    "catalog_page": "/data/impa-catalog-pages/cleaning.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Cleaning",
      "Form": "Liquid / bulk",
      "Flash Point": "> 60°C",
      "Dilution": "Ready to use"
    }
  },
  {
    "impa_code": "331502",
    "code": "331502",
    "name": "Rag Cotton Industrial",
    "unit": "KG",
    "category": "Cleaning",
    "rob": 25,
    "catalog_page": "/data/impa-catalog-pages/cleaning.svg",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Cleaning",
      "Form": "Liquid / bulk",
      "Flash Point": "> 60°C",
      "Dilution": "Ready to use"
    }
  }
];
