/** IMPA STORE seed — generated by scripts/build-impa-catalog.mjs */
export type ImpaSeedItem = {
  impa_code: string;
  code: string;
  name: string;
  unit: string;
  category: string;
  rob: number;
  plate_id: string;
  plate_no: string;
  specs: Record<string, string>;
};

export const IMPA_SEED: ImpaSeedItem[] = [
  {
    "impa_code": "330101",
    "code": "330101",
    "name": "Rope Manila 32mm",
    "unit": "COIL",
    "category": "Rigging",
    "rob": 4,
    "plate_id": "PL-33-01",
    "plate_no": "PL-33-01",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Rigging",
      "Material": "Manila hemp 3-strand",
      "Standard": "ISO 1140 / ISO 2408",
      "Dimensions": "Ø32 mm × 220 m coil",
      "Breaking Load": "≥ 32 kN"
    }
  },
  {
    "impa_code": "330102",
    "code": "330102",
    "name": "Wire Rope 12mm Galvanized",
    "unit": "MTR",
    "category": "Rigging",
    "rob": 120,
    "plate_id": "PL-33-01",
    "plate_no": "PL-33-01",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Rigging",
      "Material": "Galvanized steel wire",
      "Standard": "ISO 1140 / ISO 2408",
      "Dimensions": "Ø12 mm × coil",
      "Breaking Load": "≥ 78 kN"
    }
  },
  {
    "impa_code": "330201",
    "code": "330201",
    "name": "Shackle Bow Type 25T",
    "unit": "PCS",
    "category": "Rigging",
    "rob": 12,
    "plate_id": "PL-33-02",
    "plate_no": "PL-33-02",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Rigging",
      "Material": "Alloy steel, hot-dip galvanized",
      "Standard": "ISO 1140 / ISO 2408",
      "Dimensions": "WLL 25 t · bow type",
      "Breaking Load": "SWL 25 t"
    }
  },
  {
    "impa_code": "330301",
    "code": "330301",
    "name": "Paint Antifouling Red",
    "unit": "LTR",
    "category": "Paint",
    "rob": 80,
    "plate_id": "PL-33-03",
    "plate_no": "PL-33-03",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Paint",
      "Material": "Marine-grade coating",
      "Standard": "IMO PSPC / ISO 12944",
      "Dimensions": "20 L pail",
      "Finish": "Matte antifouling",
      "Coverage": "8–10 m²/L",
      "VOC": "< 400 g/L"
    }
  },
  {
    "impa_code": "330302",
    "code": "330302",
    "name": "Paint Primer Epoxy Grey",
    "unit": "LTR",
    "category": "Paint",
    "rob": 45,
    "plate_id": "PL-33-03",
    "plate_no": "PL-33-03",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Paint",
      "Material": "Marine-grade coating",
      "Standard": "IMO PSPC / ISO 12944",
      "Dimensions": "20 L pail",
      "Finish": "Epoxy primer",
      "Coverage": "8–10 m²/L",
      "VOC": "< 400 g/L"
    }
  },
  {
    "impa_code": "330401",
    "code": "330401",
    "name": "Brush Paint 100mm",
    "unit": "PCS",
    "category": "Paint",
    "rob": 24,
    "plate_id": "PL-33-04",
    "plate_no": "PL-33-04",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Paint",
      "Material": "Hog bristle / hardwood handle",
      "Standard": "IMO PSPC / ISO 12944",
      "Dimensions": "100 mm bristle width",
      "Finish": "Application tool",
      "Coverage": "—",
      "VOC": "—"
    }
  },
  {
    "impa_code": "330501",
    "code": "330501",
    "name": "Grease Multi-Purpose NLGI 2",
    "unit": "KG",
    "category": "Lubricants",
    "rob": 36,
    "plate_id": "PL-33-05",
    "plate_no": "PL-33-05",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Lubricants",
      "Material": "Lithium complex grease",
      "Standard": "NLGI GC-LB",
      "Dimensions": "18 kg pail",
      "Grade": "NLGI 2",
      "Operating Temp": "-20°C to +120°C"
    }
  },
  {
    "impa_code": "330502",
    "code": "330502",
    "name": "Hydraulic Oil ISO 46",
    "unit": "LTR",
    "category": "Lubricants",
    "rob": 200,
    "plate_id": "PL-33-05",
    "plate_no": "PL-33-05",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Lubricants",
      "Material": "Mineral hydraulic base oil",
      "Standard": "ISO 6743-4 / DIN 51524",
      "Dimensions": "208 L drum / bulk",
      "Grade": "ISO VG 46",
      "Operating Temp": "-20°C to +120°C"
    }
  },
  {
    "impa_code": "330601",
    "code": "330601",
    "name": "Filter Oil Engine",
    "unit": "PCS",
    "category": "Engine",
    "rob": 6,
    "plate_id": "PL-33-06",
    "plate_no": "PL-33-06",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Engine",
      "Material": "Cellulose / synthetic media",
      "Standard": "OEM / ISO 4548 (filters)",
      "Dimensions": "OEM spin-on cartridge",
      "Voltage": "—",
      "Application": "Engine lube / fuel filtration",
      "Service Interval": "Per PMS running hours"
    }
  },
  {
    "impa_code": "330602",
    "code": "330602",
    "name": "Filter Fuel Primary",
    "unit": "PCS",
    "category": "Engine",
    "rob": 4,
    "plate_id": "PL-33-06",
    "plate_no": "PL-33-06",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Engine",
      "Material": "Cellulose / synthetic media",
      "Standard": "OEM / ISO 4548 (filters)",
      "Dimensions": "OEM spin-on cartridge",
      "Voltage": "—",
      "Application": "Engine lube / fuel filtration",
      "Service Interval": "Per PMS running hours"
    }
  },
  {
    "impa_code": "330701",
    "code": "330701",
    "name": "Gasket Set Cylinder Head",
    "unit": "SET",
    "category": "Engine",
    "rob": 1,
    "plate_id": "PL-33-07",
    "plate_no": "PL-33-07",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Engine",
      "Material": "Multi-layer steel & composite",
      "Standard": "OEM / ISO 4548 (filters)",
      "Dimensions": "Cylinder head set",
      "Voltage": "—",
      "Application": "OEM replacement",
      "Service Interval": "Per PMS running hours"
    }
  },
  {
    "impa_code": "330801",
    "code": "330801",
    "name": "Belt V-Type A-65",
    "unit": "PCS",
    "category": "Engine",
    "rob": 3,
    "plate_id": "PL-33-08",
    "plate_no": "PL-33-08",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Engine",
      "Material": "Chloroprene rubber",
      "Standard": "OEM / ISO 4548 (filters)",
      "Dimensions": "A-65 V-belt profile",
      "Voltage": "—",
      "Application": "OEM replacement",
      "Service Interval": "Per PMS running hours"
    }
  },
  {
    "impa_code": "330901",
    "code": "330901",
    "name": "Safety Helmet White",
    "unit": "PCS",
    "category": "Safety",
    "rob": 18,
    "plate_id": "PL-33-09",
    "plate_no": "PL-33-09",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Safety",
      "Material": "ABS / HDPE shell",
      "Standard": "ISO 12402",
      "Dimensions": "Standard size",
      "Certification": "ISO / CE marked",
      "Voltage": "—"
    }
  },
  {
    "impa_code": "330902",
    "code": "330902",
    "name": "Safety Gloves Leather",
    "unit": "PR",
    "category": "Safety",
    "rob": 30,
    "plate_id": "PL-33-09",
    "plate_no": "PL-33-09",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Safety",
      "Material": "Split leather",
      "Standard": "ISO 12402",
      "Dimensions": "Standard size",
      "Certification": "ISO / CE marked",
      "Voltage": "—"
    }
  },
  {
    "impa_code": "331001",
    "code": "331001",
    "name": "Life Jacket SOLAS",
    "unit": "PCS",
    "category": "Safety",
    "rob": 28,
    "plate_id": "PL-33-10",
    "plate_no": "PL-33-10",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Safety",
      "Material": "ABS / HDPE shell",
      "Standard": "SOLAS / MED",
      "Dimensions": "Adult universal",
      "Certification": "SOLAS Ch. III",
      "Voltage": "—"
    }
  },
  {
    "impa_code": "331101",
    "code": "331101",
    "name": "Fire Extinguisher CO2 5kg",
    "unit": "PCS",
    "category": "Safety",
    "rob": 8,
    "plate_id": "PL-33-11",
    "plate_no": "PL-33-11",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Safety",
      "Material": "Steel cylinder / brass valve",
      "Standard": "EN 3 / MED",
      "Dimensions": "CO₂ 5 kg portable",
      "Certification": "ISO / CE marked",
      "Voltage": "—"
    }
  },
  {
    "impa_code": "331201",
    "code": "331201",
    "name": "Valve Gate Bronze 50mm",
    "unit": "PCS",
    "category": "Piping",
    "rob": 5,
    "plate_id": "PL-33-12",
    "plate_no": "PL-33-12",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Piping",
      "Material": "Bronze body / stainless trim",
      "Standard": "ISO 7005 / PN16",
      "Dimensions": "DN50 (2\") · face-to-face 180 mm",
      "Pressure Class": "PN16",
      "Body Material": "Bronze / gunmetal"
    }
  },
  {
    "impa_code": "331202",
    "code": "331202",
    "name": "Flange Blind 50mm",
    "unit": "PCS",
    "category": "Piping",
    "rob": 4,
    "plate_id": "PL-33-12",
    "plate_no": "PL-33-12",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Piping",
      "Material": "Bronze body / stainless trim",
      "Standard": "ISO 7005 / PN16",
      "Dimensions": "DN50 (2\") · face-to-face 180 mm",
      "Pressure Class": "PN16",
      "Body Material": "Bronze / gunmetal"
    }
  },
  {
    "impa_code": "331301",
    "code": "331301",
    "name": "Bolt Hex M16 x 60",
    "unit": "PCS",
    "category": "Fasteners",
    "rob": 150,
    "plate_id": "PL-33-13",
    "plate_no": "PL-33-13",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Fasteners",
      "Material": "Alloy steel, zinc plated",
      "Standard": "ISO 4014 / DIN 931",
      "Dimensions": "M16 × 60 mm hex",
      "Thread": "M16 × 2.0",
      "Grade": "8.8 / A4-80"
    }
  },
  {
    "impa_code": "331302",
    "code": "331302",
    "name": "Nut Hex M16",
    "unit": "PCS",
    "category": "Fasteners",
    "rob": 160,
    "plate_id": "PL-33-13",
    "plate_no": "PL-33-13",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Fasteners",
      "Material": "Alloy steel, zinc plated",
      "Standard": "ISO 4014 / DIN 931",
      "Dimensions": "M16 hex nut",
      "Thread": "M16 × 2.0",
      "Grade": "8.8 / A4-80"
    }
  },
  {
    "impa_code": "331401",
    "code": "331401",
    "name": "Electrical Cable 3C 2.5mm²",
    "unit": "MTR",
    "category": "Electrical",
    "rob": 250,
    "plate_id": "PL-33-14",
    "plate_no": "PL-33-14",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Electrical",
      "Material": "Copper conductor, PVC sheath",
      "Standard": "IEC 60227 / IEC 60092",
      "Dimensions": "3C × 2.5 mm²",
      "Voltage": "220 V AC / 60 Hz",
      "Insulation": "PVC 3-core",
      "Rating": "2.5 mm² / 20 A"
    }
  },
  {
    "impa_code": "331402",
    "code": "331402",
    "name": "Lamp Fluorescent 20W",
    "unit": "PCS",
    "category": "Electrical",
    "rob": 20,
    "plate_id": "PL-33-14",
    "plate_no": "PL-33-14",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Electrical",
      "Material": "Glass tube / phosphor coating",
      "Standard": "IEC 60227 / IEC 60092",
      "Dimensions": "T8 20 W tube",
      "Voltage": "220 V AC / 60 Hz",
      "Insulation": "—",
      "Rating": "20 W"
    }
  },
  {
    "impa_code": "331501",
    "code": "331501",
    "name": "Cleaning Compound Degreaser",
    "unit": "LTR",
    "category": "Cleaning",
    "rob": 60,
    "plate_id": "PL-33-15",
    "plate_no": "PL-33-15",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Cleaning",
      "Material": "Industrial degreaser base",
      "Standard": "IMO / MARPOL compliant",
      "Dimensions": "Bulk liquid",
      "Flash Point": "> 60°C",
      "Form": "Ready to use"
    }
  },
  {
    "impa_code": "331502",
    "code": "331502",
    "name": "Rag Cotton Industrial",
    "unit": "KG",
    "category": "Cleaning",
    "rob": 25,
    "plate_id": "PL-33-15",
    "plate_no": "PL-33-15",
    "specs": {
      "IMPA Edition": "7th",
      "Catalog Section": "Cleaning",
      "Material": "Industrial degreaser base",
      "Standard": "IMO / MARPOL compliant",
      "Dimensions": "Bulk liquid",
      "Flash Point": "> 60°C",
      "Form": "Ready to use"
    }
  }
];
